/**
 * Generate ADMIN_PASSWORD (UUID) and SESSION_SECRET for local auth.
 * Writes to .env.local; run: npm run generate-admin-credentials
 */

import * as crypto from "crypto";
import * as fs from "fs";
import * as path from "path";

const projectRoot = path.resolve(__dirname, "..");
const envLocalPath = path.join(projectRoot, ".env.local");
const envExamplePath = path.join(projectRoot, ".env.example");

const ADMIN_PASSWORD = crypto.randomUUID();
const SESSION_SECRET = crypto.randomBytes(32).toString("hex");

function readEnvFile(filePath: string): string[] {
  if (!fs.existsSync(filePath)) return [];
  return fs.readFileSync(filePath, "utf8").split("\n");
}

function parseAndUpdate(lines: string[]): string[] {
  const keysToReplace = new Set(["ADMIN_PASSWORD", "SESSION_SECRET", "ADMIN_USERNAME"]);
  const otherLines: string[] = [];

  for (const line of lines) {
    const match = line.match(/^([A-Z_]+)=/);
    if (match && keysToReplace.has(match[1])) {
      continue; // skip, we'll add our own
    }
    otherLines.push(line);
  }

  // Trim trailing blank lines, then add auth vars
  while (otherLines.length > 0 && otherLines[otherLines.length - 1].trim() === "") {
    otherLines.pop();
  }
  otherLines.push("");
  otherLines.push("# Admin auth (generated by generate-admin-credentials)");
  otherLines.push("ADMIN_USERNAME=admin");
  otherLines.push(`ADMIN_PASSWORD=${ADMIN_PASSWORD}`);
  otherLines.push(`SESSION_SECRET=${SESSION_SECRET}`);
  otherLines.push("");
  return otherLines;
}

function main() {
  let lines: string[];
  if (fs.existsSync(envLocalPath)) {
    lines = readEnvFile(envLocalPath);
  } else if (fs.existsSync(envExamplePath)) {
    lines = readEnvFile(envExamplePath);
  } else {
    lines = [];
  }

  const updated = parseAndUpdate(lines);
  fs.writeFileSync(envLocalPath, updated.join("\n"));
  console.log("Updated .env.local with admin credentials.");
  console.log("");
  console.log("Generated ADMIN_PASSWORD (save this):");
  console.log(ADMIN_PASSWORD);
  console.log("");
  console.log("Restart the dev server after changing env vars.");
}

main();
